# Generated by Django 6.0.3 on 2026-03-19 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('input_name', models.CharField(max_length=512)),
                ('input_ext', models.CharField(max_length=16)),
                ('output_format', models.CharField(max_length=16)),
                ('strategy', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(max_length=32)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.FloatField()),
                ('completed_at', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=64, unique=True)),
                ('first_seen', models.FloatField()),
                ('last_seen', models.FloatField()),
                ('visit_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='CreditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('package_key', models.CharField(max_length=32)),
                ('credits', models.IntegerField()),
                ('amount_centavos', models.IntegerField()),
                ('paymongo_source_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(blank=True, default='', max_length=64)),
                ('credits', models.IntegerField(default=0)),
                ('free_used_month', models.IntegerField(default=0)),
                ('free_reset_month', models.CharField(default='', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
