# Generated by Django 5.2.8 on 2026-03-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('input_name', models.CharField(max_length=512)),
                ('input_ext', models.CharField(max_length=16)),
                ('output_format', models.CharField(max_length=16)),
                ('strategy', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(max_length=32)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.FloatField()),
                ('completed_at', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
