# Generated by Django 5.2.8 on 2026-03-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=64, unique=True)),
                ('first_seen', models.FloatField()),
                ('last_seen', models.FloatField()),
                ('visit_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
