# Generated by Django 5.2.8 on 2026-03-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_visitor_alter_jobrecord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=64, unique=True)),
                ('credits', models.IntegerField(default=0)),
                ('free_used_month', models.IntegerField(default=0)),
                ('free_reset_month', models.CharField(default='', max_length=7)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
