# Generated by Django 6.0.3 on 2026-03-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('package_key', models.CharField(max_length=32)),
                ('credits', models.IntegerField()),
                ('amount_centavos', models.IntegerField()),
                ('paymongo_source_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
