# Generated by Django 6.0.3 on 2026-05-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
