# Generated by Django 6.0.3 on 2026-05-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('export-quality', 'Export Quality'), ('speed', 'Conversion Speed'), ('ai-chat', 'Export AI'), ('ui', 'Interface / Usability'), ('bug', 'Bug Report'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
