# Generated by Django 6.0.3 on 2026-05-20 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_feedback_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Feedback'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='job',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('export-quality', 'Export quality'), ('speed', 'Conversion speed'), ('ai-chat', 'Export AI'), ('ui', 'Interface / usability'), ('bug', 'Bug report'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
